application: bstockus-assignments
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: assignments_server.application    

- url: /web/
  static_dir: webclient
  
- url: /.*
  script: assignments_server.application